table Retail

	column 'Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Category

	column 'Price'
		dataType: double
		summarizeBy: none
		sourceColumn: Price

	column 'Stock'
		dataType: double
		summarizeBy: none
		sourceColumn: Stock

	measure KPI_RegistrosRetail = COUNTROWS(Retail)
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_PrecioRetail = AVERAGE(Retail[Price])
		formatString: #,0.00
		displayFolder: Indicadores

	partition Retail = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Retail.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Category", type text}, {"Price", type number}, {"Stock", type number}}, "en-US")
				in
				    Typed
