table SesionesCaballos

	column 'event_time'
		dataType: string
		summarizeBy: none
		sourceColumn: event_time

	column 'event_type'
		dataType: string
		summarizeBy: none
		sourceColumn: event_type

	column 'horse_id'
		dataType: double
		summarizeBy: none
		sourceColumn: horse_id

	measure KPI_RegistrosSesionesCaballos = COUNTROWS(SesionesCaballos)
		formatString: #,0.00
		displayFolder: Indicadores

	partition SesionesCaballos = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "SesionesCaballos.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"event_time", type text}, {"event_type", type text}, {"horse_id", type number}}, "en-US")
				in
				    Typed
