table SesionesRetail

	column 'event_time'
		dataType: string
		summarizeBy: none
		sourceColumn: event_time

	column 'event_type'
		dataType: string
		summarizeBy: none
		sourceColumn: event_type

	column 'item_id'
		dataType: double
		summarizeBy: none
		sourceColumn: item_id

	measure KPI_RegistrosSesionesRetail = COUNTROWS(SesionesRetail)
		formatString: #,0.00
		displayFolder: Indicadores

	partition SesionesRetail = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "SesionesRetail.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"event_time", type text}, {"event_type", type text}, {"item_id", type number}}, "en-US")
				in
				    Typed
