table Usuarios

	column 'first_seen'
		dataType: string
		summarizeBy: none
		sourceColumn: first_seen

	column 'country'
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column 'city'
		dataType: string
		summarizeBy: none
		sourceColumn: city

	column 'traffic_source'
		dataType: string
		summarizeBy: none
		sourceColumn: traffic_source

	column 'gender'
		dataType: string
		summarizeBy: none
		sourceColumn: gender

	column 'device_type'
		dataType: string
		summarizeBy: none
		sourceColumn: device_type

	column 'job_info'
		dataType: string
		summarizeBy: none
		sourceColumn: job_info

	measure KPI_RegistrosUsuarios = COUNTROWS(Usuarios)
		formatString: #,0.00
		displayFolder: Indicadores

	partition Usuarios = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Usuarios.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"first_seen", type text}, {"country", type text}, {"city", type text}, {"traffic_source", type text}, {"gender", type text}, {"device_type", type text}, {"job_info", type text}}, "en-US")
				in
				    Typed
